version: '3'

services:
    asciidoctor:
        image: asciidoctor/docker-asciidoctor

        volumes:
          - ./content:/documents
          - ./docs:/html

    html:
        image: asciidoctor/docker-asciidoctor

        volumes:
          - ./content:/documents
          - ./docs:/html

        command: asciidoctor -o /html/index.html -d book index.adoc

    pdf:
        image: asciidoctor/docker-asciidoctor

        volumes:
          - ./content:/documents
          - ./docs:/html

        command: asciidoctor-pdf -o /html/index.pdf -d book index.adoc

    epub:
        image: asciidoctor/docker-asciidoctor

        volumes:
          - ./content:/documents
          - ./docs:/html

        command: asciidoctor-epub3 -o /html/index.epub -d book index.adoc