version: '3'

services:
    pandoc:
        build: "."

        volumes:
          - ./content:/source
          - ./docs:/html
          - ./:/book

    asciidoctor:
        image: asciidoctor/docker-asciidoctor

        volumes:
          - ./content:/documents

    html:
        image: asciidoctor/docker-asciidoctor

        volumes:
        - ./content:/documents


