== Shared Nothing Design

One of the most interesting aspects of Cassandra is that it's designed to run on cheap hardware and scales horizontally rather than vertically.  That means instead of buying more and more expensive servers we buy a bunch of cheap servers.  We don't rely on expensive SANs or other types of complex shared storage.

Each node should have it's own storage, and ideally be dedicated hardware.  While it's possible to run Cassandra on virtual machines, usually that's just adding unnecessary overhead.

Given the choice, if you're buying your own hardware, opt for a simple design.  That doesn't mean use your old Pentium desktops and 5400 RPM disks though.

TIP: It's easy to want to use epic hardware when setting up your Cassandra cluster, but it's unnecessary.  We recommend aiming for 8-16 CPU threads and 32-64 GB RAM.  We recommend using SSDs, they've come down a lot in price a ton and make a huge difference.  Friends don't let friends use spinning rust.


=== Token Ring


At a high level, Cassandra can be thought of as a distributed hash table.  Every row of data, like a relational database, contains a <<Primary Key>>.  The primary key has two components, a <<Partition Key>> and zero or more <<Clustering Keys>>.

To determine which <<Replicas>> a partition lives on, we take a hash of all the components of the key, and that is used to generate a <<Token>>.

The default partitioner in modern Cassandra is the <<Murmur3Partitioner>>.  There's no practical reason to change this other than if your cluster has been running since before Murmur3Partitioner was the default.

Murmur3Partitioner will generate a token between -2 ^ 63 and 2 ^ 63 - 1

Each node has at least 1 token.

More tokens means more peers.  Most keyspaces use an RF of 3.  Each token gives RF+1 peers.

I recommend setting `num_tokens:4` and use `allocate_tokens_for_keyspace` to ensure even distribution of data throughout the ring.










